---
title: 'Motivating Employee Ideas Through Contests: Field Experimental Evidence'
author: Andrea Blasco | ablasco@fas.harvard
date: 13th Open And User Innovation Society Meeting, July 2015
handout: true
fontsize: 12pt
fontfamily: fourier
bibliography: /Users/andrea/NTL/Literature/library.bib
csl: /Users/andrea/Data/styles-distribution/european-journal-of-political-research.csl
---
